title: WinFsp
copyright: © 2020 Bill Zissimopoulos
baseURL: https://winfsp.github.io

theme: primer

disableHugoGeneratorInject: true
disableKinds: ["taxonomy", "taxonomyTerm", "RSS", "404"]
disablePathToLower: true
pygmentsUseClasses: true
relativeURLs: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  description: Windows File System Proxy - FUSE for Windows
  logo: logo.png

menu:
  main:
  - name: Home
    url: /
    weight: 10
  - name: Download
    url: /rel
    weight: 20
  - name: API Reference
    url: /apiref
    weight: 25
  - name: Documentation
    url: /doc
    post: pages
    weight: 30
  - name: Source
    url: /src
    weight: 40
