baseURL: https://winfsp.github.io
title: WinFsp
copyright: © 2020 Bill Zissimopoulos

theme: primer

disableHugoGeneratorInject: true
disablePathToLower: true
disableKinds: ["taxonomy", "taxonomyTerm", "RSS", "404"]
pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  logo: logo.png
  description: Windows File System Proxy - FUSE for Windows

menu:
  main:
  - name: Main
    url: /
    weight: 10
  - name: Download
    url: /rel
    weight: 20
  - name: API Reference
    url: /doc/WinFsp-API-winfsp.h
    post: disable-current
    weight: 25
  - name: Documentation
    url: /doc
    post: pages
    weight: 30
  - name: Source
    url: /src
    weight: 40
