baseURL: https://winfsp.github.io
title: WinFsp
copyright: © 2020 Bill Zissimopoulos

theme: primer

disableHugoGeneratorInject: true
disablePathToLower: true
disableKinds: ["taxonomy", "taxonomyTerm", "RSS", "404"]

params:
  logo: logo.png
  description: Windows File System Proxy - FUSE for Windows

menu:
  main:
  - name: Main
    url: /
    weight: 10
  - name: Download
    url: /rel/
    weight: 20
  - name: API Reference
    url: /apiref/
    weight: 30
  - name: Documentation
    url: /doc/
    weight: 40
  - name: Source
    url: /src/
    weight: 50
  - name: Blog
    url: /blog/
    weight: 60
