#!/bin/bash

set -e

copy_content()
{
    local src="$1"
    local bnm=${src##*/}
    local nam=${bnm%.*}
    local tit=${nam//-/ }
    local dir=${src%.*}
    local dst="$2"
    local cmd="$3"

    local end="---"
    if [[ $nam == "WinFsp-API-"* ]]; then
        end='no_heading: true
---'
    fi
    tit="${tit/WinFsp API /WinFsp API: }"

    cat <<EOT | cat - "$src" | eval "$3" > "$dst"/"$bnm"
---
title: '$tit'
$end
EOT

    if [ -d "$dir" ]; then
        cp -R "$dir" "$dst"
    fi
}

copy_asciidoc()
{
    local nl=\\$'\n'
    copy_content "$1" "$2" 'sed -e "s/$nam\///g" -e "1,/^= .*$/s/^\\(= .*\\)$/\\1$nl:source-highlighter: pygments/"'
}

copy_markdown()
{
    local nl=\\$'\n'
    copy_content "$1" "$2" 'cat'
}

cd $(dirname "$0")/..

rm -rf content/doc
mkdir -p content/doc

cat <<EOT | cat - ext/winfsp/doc/Home.md | sed -e '/^# .*$/d' -e '/^\[\[[^]]*.png\]\]$/d' -e 's/\[\[\([^|]*\)|\([^]]*\)]]/[\1](\2)/g' > content/doc/_index.md
---
title: 'Documentation'
---
EOT

for f in ext/winfsp/doc/*.asciidoc; do
    copy_asciidoc "$f" content/doc
done

for f in ext/winfsp/doc/*.h.md; do
    copy_asciidoc "$f" content/doc
done
